=== xianlaioy/amoeba/trunk/amoeba/src/java/com/meidusa/amoeba/xml/amoeba.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT className ( #PCDATA ) >
<!ELEMENT amoeba:configuration ( server, connectionManagerList, dbServerList, queryRouter ) >
<!ATTLIST amoeba:configuration
  xmlns:amoeba CDATA #FIXED "http://amoeba.meidusa.com/" 
>

<!ELEMENT connectionManagerList ( connectionManager+ ) >

<!ELEMENT connectionManager ( className? ,property* ) >
<!ATTLIST connectionManager name NMTOKEN #REQUIRED >
<!ATTLIST connectionManager class NMTOKEN #IMPLIED >

<!ELEMENT dbServer ( factoryConfig?, poolConfig* ) >
<!ATTLIST dbServer name NMTOKEN #REQUIRED >
<!ATTLIST dbServer virtual NMTOKEN #IMPLIED >

<!ELEMENT dbServerList ( dbServer+ ) >

<!ELEMENT factoryConfig ( className? ,property* ) >
<!ATTLIST factoryConfig class NMTOKEN #IMPLIED >

<!ELEMENT poolConfig ( className? ,property* ) >
<!ATTLIST poolConfig class NMTOKEN #IMPLIED >

<!ELEMENT property ( #PCDATA | bean)* >

<!ELEMENT bean ( className?,property*) >
<!ATTLIST bean name NMTOKEN #IMPLIED >
<!ATTLIST bean class NMTOKEN #IMPLIED >

<!ATTLIST property name CDATA #REQUIRED >

<!ATTLIST queryRouter class NMTOKEN #IMPLIED >

<!ELEMENT queryRouter ( className?, property*) >

<!ELEMENT server ( property+ ) >

=== xianlaioy/amoeba/trunk/build/build-oracle/conf/amoeba.xml
<?xml version="1.0" encoding="gbk"?>
<!DOCTYPE amoeba:configuration SYSTEM "amoeba.dtd">

<amoeba:configuration xmlns:amoeba="http://amoeba.meidusa.com/">
    <!--proxy server config-->
    <server>
        <property name="port">8066</property>
        <property name="ipAddress">127.0.0.1</property>
        <property name="readThreadPoolSize">20</property>
        <property name="clientSideThreadPoolSize">30</property>
        <property name="serverSideThreadPoolSize">30</property>
        <property name="netBufferSize">100</property>
        <property name="tcpNoDelay">true</property>
        <property name="user">root</property>
        <property name="password">12345</property>
    </server>

    <!--connectionManagerList-->
    <connectionManagerList>
        <connectionManager name="defaultManager" class="com.meidusa.amoeba.net.AuthingableConnectionManager"/>
    </connectionManagerList>

    <!--dbServerList-->
    <dbServerList>
        <dbServer name="default">
            <factoryConfig class="com.meidusa.amoeba.oracle.net.OracleServerConnectionFactory">
                <property name="manager">defaultManager</property>
                <property name="port">1521</property>
                <property name="ipAddress">[ipAddress]</property>
                <property name="schema">[schema]</property>
                <property name="user">[user]</property>
                <property name="password">[password]</property>
            </factoryConfig>
            <!-- ObjectPool实现类 -->
            <poolConfig class="com.meidusa.amoeba.net.poolable.PoolableObjectPool">
                <property name="maxActive">200</property>
                <property name="maxIdle">200</property>
                <property name="minIdle">10</property>
                <property name="minEvictableIdleTimeMillis">600000</property>
                <property name="timeBetweenEvictionRunsMillis">600000</property>
                <property name="testOnBorrow">true</property>
                <property name="testWhileIdle">false</property>
            </poolConfig>
        </dbServer>
        <dbServer name="multiPool" virtual="true">
            <poolConfig class="com.meidusa.amoeba.server.MultipleServerPool">
                <!--
                                               负载均衡参数 1=ROUNDROBIN , 2=WEIGHTBASED
                -->
                <property name="loadbalance">1</property>
                <!--
                                               参与该pool负载均衡的poolName列表以逗号分割
                -->
                <property name="poolNames">default</property>
            </poolConfig>
        </dbServer>
    </dbServerList>

    <!-- queryRouter -->
    <queryRouter class="com.meidusa.amoeba.oracle.parser.OracleQueryRouter">
        <property name="ruleConfig">${amoeba.home}/conf/rule.xml</property>
        <property name="functionConfig">${amoeba.home}/conf/functionMap.xml</property>
        <property name="ruleFunctionConfig">${amoeba.home}/conf/ruleFunctionMap.xml</property>
        <property name="LRUMapSize">1500</property>
        <property name="defaultPool">default</property>
        <property name="needParse">true</property>
    </queryRouter>
</amoeba:configuration>

=== xianlaioy/amoeba/trunk/build/build-aladdin/conf/amoeba.xml
<?xml version="1.0" encoding="gbk"?>

<!DOCTYPE amoeba:configuration SYSTEM "amoeba.dtd">
<amoeba:configuration xmlns:amoeba="http://amoeba.meidusa.com/">

	<server>
		<!-- proxy server绑定的端口 -->
		<property name="port">8066</property>
		
		<!-- proxy server绑定的IP -->
		<property name="ipAddress">127.0.0.1</property>
		
		<!-- proxy server net IO Read thread size -->
		<property name="readThreadPoolSize">20</property>
		
		<!-- proxy server client process thread size -->
		<property name="clientSideThreadPoolSize">30</property>
		
		<!-- mysql server data packet process thread size -->
		<property name="serverSideThreadPoolSize">30</property>
		
		<!-- socket Send and receive BufferSize(unit:K)  -->
		<property name="netBufferSize">100</property>
		
		<!-- Enable/disable TCP_NODELAY (disable/enable Nagle's algorithm). -->
		<property name="tcpNoDelay">true</property>
		
		<!-- 对外验证的用户名 -->
		<property name="user">root</property>
		
		<!-- 对外验证的密码 -->
		<!--
		<property name="password">password</property>
		-->
	</server>
	
	<!-- 
		每个ConnectionManager都将作为一个线程启动。
		manager负责Connection IO读写/死亡检测
	-->
	<connectionManagerList>
		<connectionManager name="defaultManager" class="com.meidusa.amoeba.net.AuthingableConnectionManager"/>
	</connectionManagerList>
	
	<dbServerList>
		<!-- 
			一台mysqlServer 需要配置一个pool，
			如果多台 平等的mysql需要进行loadBalance， 
			平台已经提供一个具有负载均衡能力的objectPool：com.meidusa.amoeba.mysql.server.MultipleServerPool
			简单的配置是属性加上 virtual="true",该Pool 不允许配置factoryConfig
			或者自己写一个ObjectPool。
		-->
		<dbServer name="server1">
			
			<!-- PoolableObjectFactory实现类 -->
			<factoryConfig class="com.meidusa.amoeba.net.jdbc.JdbcConnectionFactory">
				
				<!-- driver name -->
				<property name="driverName">com.mysql.jdbc.Driver</property>
				
				<!-- url -->
				<property name="properties">
					<bean class="java.util.Properties">
						<!-- 用于登陆mysql的用户名 -->
						<property name="user">root</property>
						
						<!-- 用于登陆mysql的密码 -->
						<!--
						<property name="password">password</property>
						-->
					</bean>
				</property>
				
			</factoryConfig>
			
			<!-- ObjectPool实现类 -->
			<poolConfig class="com.meidusa.amoeba.net.poolable.PoolableObjectPool">
				<property name="maxActive">200</property>
				<property name="maxIdle">200</property>
				<property name="minIdle">10</property>
				<property name="minEvictableIdleTimeMillis">600000</property>
				<property name="timeBetweenEvictionRunsMillis">600000</property>
				<property name="testOnBorrow">true</property>
				<property name="testWhileIdle">true</property>
			</poolConfig>
		</dbServer>
		
		
		<dbServer name="multiPool" virtual="true">
			<poolConfig class="com.meidusa.amoeba.server.MultipleServerPool">
				<!-- 负载均衡参数 1=ROUNDROBIN , 2=WEIGHTBASED -->
				<property name="loadbalance">1</property>
				
				<!-- 参与该pool负载均衡的poolName列表以逗号分割 -->
				<property name="poolNames">server1</property>
			</poolConfig>
		</dbServer>
		
	</dbServerList>
	
	<queryRouter class="com.meidusa.amoeba.aladdin.parser.AladdinQueryRouter">
		<property name="ruleConfig">${amoeba.home}/conf/rule.xml</property>
		<property name="functionConfig">${amoeba.home}/conf/functionMap.xml</property>
		<property name="ruleFunctionConfig">${amoeba.home}/conf/ruleFunctionMap.xml</property>
		<property name="LRUMapSize">1500</property>
		<property name="defaultPool">server1</property>
		
		<!--
		<property name="writePool">server1</property>
		<property name="readPool">server1</property>
		-->
		<property name="needParse">true</property>
	</queryRouter>
</amoeba:configuration>

=== xianlaioy/amoeba/trunk/build/conf/amoeba.xml
<?xml version="1.0" encoding="gbk"?>

<!DOCTYPE amoeba:configuration SYSTEM "amoeba.dtd">
<amoeba:configuration xmlns:amoeba="http://amoeba.meidusa.com/">

	<server>
		<!-- proxy server绑定的端口 -->
		<property name="port">8066</property>
		
		<!-- proxy server绑定的IP -->
		<property name="ipAddress">127.0.0.1</property>
		
		<!-- proxy server net IO Read thread size -->
		<property name="readThreadPoolSize">100</property>
		
		<!-- proxy server client process thread size -->
		<property name="clientSideThreadPoolSize">80</property>
		
		<!-- mysql server data packet process thread size -->
		<property name="serverSideThreadPoolSize">100</property>
		
		<!-- socket Send and receive BufferSize(unit:K)  -->
		<property name="netBufferSize">100</property>
		
		<!-- Enable/disable TCP_NODELAY (disable/enable Nagle's algorithm). -->
		<property name="tcpNoDelay">false</property>
		
		<!-- 对外验证的用户名 -->
		<property name="user">root</property>
		
		<!-- 对外验证的密码 -->
		<!--
		<property name="password">password</property>
		-->
	</server>
	
	<!-- 
		每个ConnectionManager都将作为一个线程启动。
		manager负责Connection IO读写/死亡检测
	-->
	<connectionManagerList>
		<connectionManager name="defaultManager">
			<className>com.meidusa.amoeba.net.AuthingableConnectionManager</className>
		</connectionManager>
	</connectionManagerList>
	
	<dbServerList>
		<!-- 
			一台mysqlServer 需要配置一个pool，
			如果多台 平等的mysql需要进行loadBalance， 
			平台已经提供一个具有负载均衡能力的objectPool：com.meidusa.amoeba.mysql.server.MultipleServerPool
			简单的配置是属性加上 virtual="true",该Pool 不允许配置factoryConfig
			或者自己写一个ObjectPool。
		-->
		<dbServer name="server1">
			
			<!-- PoolableObjectFactory实现类 -->
			<factoryConfig>
				<className>com.meidusa.amoeba.mysql.net.MysqlServerConnectionFactory</className>
				<property name="manager">defaultManager</property>
				
				<!-- 真实mysql数据库端口 -->
				<property name="port">3306</property>
				
				<!-- 真实mysql数据库IP -->
				<property name="ipAddress">127.0.0.1</property>
				<property name="schema">test</property>
				
				<!-- 用于登陆mysql的用户名 -->
				<property name="user">root</property>
				
				<!-- 用于登陆mysql的密码 -->
				
				<!--
				<property name="password">password</property>
				-->
				
			</factoryConfig>
			
			<!-- ObjectPool实现类 -->
			<poolConfig>
				<className>com.meidusa.amoeba.net.poolable.PoolableObjectPool</className>
				<property name="maxActive">200</property>
				<property name="maxIdle">200</property>
				<property name="minIdle">10</property>
				<property name="minEvictableIdleTimeMillis">600000</property>
				<property name="timeBetweenEvictionRunsMillis">600000</property>
				<property name="testOnBorrow">true</property>
				<property name="testWhileIdle">true</property>
			</poolConfig>
		</dbServer>
		
		
		<dbServer name="multiPool" virtual="true">
			<poolConfig>
				<className>com.meidusa.amoeba.server.MultipleServerPool</className>
				<!-- 负载均衡参数 1=ROUNDROBIN , 2=WEIGHTBASED -->
				<property name="loadbalance">1</property>
				
				<!-- 参与该pool负载均衡的poolName列表以逗号分割 -->
				<property name="poolNames">server1</property>
			</poolConfig>
		</dbServer>
		
	</dbServerList>
	
	<queryRouter>
		<className>com.meidusa.amoeba.mysql.parser.MysqlQueryRouter</className>
		<property name="ruleConfig">${amoeba.home}/conf/rule.xml</property>
		<property name="functionConfig">${amoeba.home}/conf/functionMap.xml</property>
		<property name="ruleFunctionConfig">${amoeba.home}/conf/ruleFunctionMap.xml</property>
		<property name="LRUMapSize">1500</property>
		<property name="defaultPool">server1</property>
		
		<!--
		<property name="writePool">server1</property>
		<property name="readPool">server1</property>
		-->
		<property name="needParse">true</property>
	</queryRouter>
</amoeba:configuration>
